# Generated by Django 5.0.6 on 2024-05-17 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('accessoires', models.TextField(blank=True)),
                ('acheteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels_achetes', to='GestionMateriel.enseignant')),
                ('possesseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels_possedes', to='GestionMateriel.enseignant')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels_responsables', to='GestionMateriel.enseignant')),
                ('salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionMateriel.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Passation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('occasion', models.CharField(blank=True, max_length=200)),
                ('objectif_utilisation', models.TextField(blank=True)),
                ('accessoires_presents', models.BooleanField(default=True)),
                ('etat_accessoires', models.CharField(blank=True, max_length=200)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passations_a', to='GestionMateriel.enseignant')),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passations_de', to='GestionMateriel.enseignant')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionMateriel.materiel')),
                ('lieu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionMateriel.salle')),
            ],
        ),
    ]
