# Generated by Django 5.0.6 on 2024-06-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMateriel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passation',
            name='budget_annee_courante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='passation',
            name='budget_financements_exceptionnels',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='passation',
            name='budget_projets',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
