# Generated by Django 5.0.6 on 2024-06-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMateriel', '0002_passation_budget_annee_courante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passation',
            name='date',
            field=models.DateField(),
        ),
    ]
